version: '3.1'

services:
  db_server:
    image: ${DB:-mariadb:10.3}
    container_name: phpmyadmin_testing_db
    environment:
      - MYSQL_ROOT_PASSWORD=${TESTSUITE_PASSWORD:-my-secret-pw}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${TESTSUITE_PASSWORD:-my-secret-pw}"]
      interval: 1s
      timeout: 1s
      retries: 3
    volumes:
      - ./testing/testing.cnf:/etc/mysql/conf.d/testing.cnf:ro
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,size=300m

  phpmyadmin:
    build:
      context: testing/
    container_name: phpmyadmin_testing
    volumes:
      - /sessions
      - ./testing/conftest.py:/conftest.py
      - ./testing/test-docker.sh:/test-docker.sh
      - ./testing/phpmyadmin_test.py:/phpmyadmin_test.py
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=${TESTSUITE_PASSWORD:-my-secret-pw}
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      interval: 1s
      timeout: 1s
      retries: 3
    depends_on:
      db_server:
          condition: service_healthy
